name: release binary

on:
  release:
    types: [created]

env:
  GO_VERSION: 1.24

jobs:
  release-static-binary:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout interchaintest
        uses: actions/checkout@v6

      - name: Setup go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      # NOTE: make install must not be statically linked to the MakeFileInstallDirectory
      - run: cd local-interchain && go mod tidy && IGNORE_STATIC_LINK=true make install

      - run: cp $HOME/go/bin/local-ic ./local-ic
      - run: chmod +x ./local-ic

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ github.token }}
          files: |
            local-ic
